ARG OCP=4.19
ARG FBC_CONFIG=fbc/op/

FROM registry.redhat.io/openshift4/ose-operator-registry-rhel9:v${OCP}
ARG FBC_CONFIG

ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

COPY ${FBC_CONFIG} /configs

RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]

# Set specific label for the location of the declarative config root directory in the image
LABEL operators.operatorframework.io.index.configs.v1=/configs
