ARG OCP=4.19
ARG FBC_CONFIG=fbc/configs

FROM registry.redhat.io/openshift4/ose-operator-registry:v${OCP}
ARG FBC_CONFIG

ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

COPY ${FBC_CONFIG} /configs

RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]

LABEL operators.operatorframework.io.index.configs.v1=/configs
