ARG OCP=4.19

FROM registry.redhat.io/openshift4/ose-operator-registry:v${OCP}

ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

COPY fbc/op/ /configs

RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]


LABEL operators.operatorframework.io.index.configs.v1=/configs
