ARG OCP=4.19

FROM registry.redhat.io/openshift4/ose-operator-registry:v${OCP}

ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

COPY fbc/hub/ /configs

RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]

# Set specific label for the location of the declarative config root directory in the image
LABEL operators.operatorframework.io.index.configs.v1=/configs
