ARG OCP=5.0
ARG FBC_CONFIG=fbc/configs

FROM registry.redhat.io/redhat/redhat-operator-index:v${OCP}
ARG FBC_CONFIG

ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

ADD ${FBC_CONFIG} /configs

RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]

# Set specific label for the location of the declarative config root directory in the image
LABEL operators.operatorframework.io.index.configs.v1=/configs
#bump2
