api_url: https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443
namespace: rh-kmm-tenant
operand-label: ok-to-merge
bundle-label: ok-to-release

release:
  bundle:
  - operator-bundle
  - hub-operator-bundle
  operand:
  - worker
  - must-gather
  - operator
  - hub-operator
  - signing
  - webhook
