
WORKER_IMAGE:
  repo: registry.redhat.io/kmm/kernel-module-management-worker-rhel9
  pullspecfile: release-2.4/pullspecs/worker-2-4.yaml

OPERATOR_IMAGE:
  repo: registry.redhat.io/kmm/kernel-module-management-rhel9-operator
  pullspecfile: release-2.4/pullspecs/operator-2-4.yaml
HUB_OPERATOR_IMAGE:
  repo: registry.redhat.io/kmm/kernel-module-management-hub-rhel9-operator
  pullspecfile: release-2.4/pullspecs/hub-operator-2-4.yaml
MUST_GATHER_IMAGE:
  repo: registry.redhat.io/kmm/kernel-module-management-must-gather-rhel9
  pullspecfile: release-2.4/pullspecs/must-gather-2-4.yaml
SIGNING_IMAGE: 
  repo: registry.redhat.io/kmm/kernel-module-management-signing-rhel9
  pullspecfile: release-2.4/pullspecs/signing-2-4.yaml
WEBHOOK_IMAGE:
  repo: registry.redhat.io/kmm/kernel-module-management-webhook-server-rhel9
  pullspecfile: release-2.4/pullspecs/webhook-2-4.yaml


