apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/chr15p/rh-kmm-konflux2?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: 'false'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" && "fbc/**".pathChanged()
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: fbc-op-418
    appstudio.openshift.io/component: fbc-op-418
    pipelines.appstudio.openshift.io/type: build
  name: fbc-op-418-on-pull-request
  namespace: rh-kmm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-kmm-tenant/fbc-op-418:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
    - linux/ppc64le
    - linux/s390x
  - name: dockerfile
    value: /fbc/Containerfile.catalogue
  - name: opm-args
    value:
      - alpha
      - render-template
      - basic
      - --migrate-level=bundle-object-to-csv-metadata
      - "fbc/op-catalog-template.json"
  - name: opm-output-path
    value: fbc/configs/kernel-module-management/catalog.json
  - name: build-args
    value: 
    - OCP=4.18
    - FBC_CONFIG=fbc/configs
  pipelineRef:
    name: catalogue-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-fbc-op-418
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
