apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/chr15p/rh-kmm-konflux2?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: 'true'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" && "release-2.2/**".pathChanged() && !("release-2.2/pullspecs/**".pathChanged())
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: kmm-2-2
    appstudio.openshift.io/component: must-gather-2-2
    pipelines.appstudio.openshift.io/type: build
  name: must-gather-2-2-on-pull-request
  namespace: rh-kmm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: target_branch
    value: '{{target_branch}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-kmm-tenant/kmm-2-2/must-gather-2-2:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
    - linux/ppc64le
    - linux/s390x
  - name: dockerfile
    value: release-2.2/Dockerfile.must-gather
  - name: path-context
    value: .
  - name: hermetic
    value: 'true'
  - name: prefetch-input
    value: '{"type": "rpm", "path": "."}'
  - name: build-source-image
    value: 'true'
  - name: build-args-file
    value: "release-2.2/build_settings.conf"
  taskRunSpecs:
  - pipelineTaskName: prefetch-dependencies
    computeResources:
      requests:
        memory: 4Gi
      limits:
        memory: 4Gi
  pipelineRef:
    name: kmm-multi-arch-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-must-gather-2-2
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
