name: Combine nudge PRs into one

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
#  SETUP:
#    runs-on: ubuntu-latest
#    #if: ${{ github.actor == 'red-hat-konflux[bot]' }}
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v7
#        with:
#          submodules: true
#          ref: ${{ github.head_ref }}

  COMBINE:
    runs-on: ubuntu-latest
    outputs:
      labelapplied: ${{ steps.combine-nudge-prs.outputs.APPLIED }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: combine-nudge-prs
        id: combine-nudge-prs
        run: python ./.github/scripts/combine_nudges.py --pr ${{ github.event.number }} --config .github/scripts/nudges.yaml  >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


  MERGE:
    needs: COMBINE
    if: ${{ needs.COMBINE.outputs.labelapplied == 'ok-to-merge' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: merge PR
        run: gh pr merge ${{ github.event.number }} --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

#      - name: merge PRs
#        run: python .github/scripts/auto_merge.py --label "ok-to-merge"
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  RELEASE:
    needs: COMBINE
    #if: ${{ needs.COMBINE.outputs.labelapplied == 'ok-to-release' }}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{ needs.COMBINE.outputs.labelapplied }}
#      - name: release operands PRs
#        run: python .github/scripts/release_nudges.py --branch ${{ github.head_ref }}  --token="${{secrets.OPENSHIFT_TOKEN}}" --config .github/scripts/nudges.yaml
#        env:
#          OPENSHIFT_TOKEN: ${{secrets.GITHUB_TOKEN}}
