name: Release images to stage

permissions:
  contents: write
  pull-requests: write

on:
  # makes workflow reusable
  workflow_dispatch:
    inputs:
      pr:
        description: "pr"
        type: string
        required: true

  workflow_call:
    inputs:
      pr:
        description: "pr"
        type: string
        required: true

jobs:
  RELEASE:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: release
        run: python scripts/release.py -t ${{secrets.KONFLUX_TOKEN}} --pr ${{ inputs.pr }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

